### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by dunnkers** [vladimiry/keepasshttp-client#1]
Hello! Thanks for this seemingly handy module. I cannot get it to work, however. The error I get when I try to `client.associate()` is:

```shell
{ Error: Bad Request
    at new NetworkResponseStatusCodeError (/Users/me/Documents/git/project/node_modules/keepasshttp-client/model/common.js:36:28)
    at KeePassHttpClient.<anonymous> (/Users/me/Documents/git/project node_modules/keepasshttp-client/client.js:133:35)
    at step (/Users/me/Documents/git/project/node_modules/tslib/tslib.js:131:27)
    at Object.next (/Users/me/Documents/git/project/node_modules/tslib/tslib.js:112:57)
    at fulfilled (/Users/me/Documents/git/project/node_modules/tslib/tslib.js:102:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) statusCode: 400 }
```

I'm using [MacPass](https://github.com/mstarke/MacPass) along with the [MacPassHTTP plugin](https://github.com/MacPass/MacPassHTTP).

Help is appreciated!

**Comment by vladimiry** [comment]
Hi @dunnkers, can you set `NODE_DEBUG=http` environment variable before running your code, that would allow to get more information for analysis. Then attach the console output here.

Besides it won't hurt if you install the Mac/DMG KeePassXC version from here https://github.com/keepassxreboot/keepassxc/releases and try to associate with it instead of MacPass. MacPass should be closed before running KeePassXC, as most likely both tools will try to listen on the same 19455 port (default keepasshttp listening port). You will need to explicitly enable the keepasshttp feature in the KeePassXC settings (Browser Integration settings tab).

PS module has been tried and successfully worked with original KeePass on Windows and KeePassXC on Linux, I've not tried running it with MacPass / MacPassHTTP stuff.

**Comment by dunnkers** [comment]
This is the shell output:
```shell
$$ NODE_DEBUG=http node test-keepass.js
HTTP 1944: call onSocket 0 0
HTTP 1944: createConnection localhost:19455: { servername: 'localhost',
  auth: null,
  path: null,
  port: '19455',
  hostname: 'localhost',
  protocol: 'http:',
  _abort: false,
  _raw: [],
  timeout: 0,
  size: 0,
  bodyUsed: false,
  body: '{"TriggerUnlock":false,"Nonce":"asdf33Ak3#JFIa==","Verifier":"HFo2fRrdfasP97Wddjb5yW+84asdfsNkYsRv3311d+I=","RequestType":"associate","Key":"FFeRaaaP6L4fsasdf382mrkdfasoNIC63aeQL+o+klVQA="}',
  agent: undefined,
  counter: 0,
  compress: true,
  follow: 20,
  url: 'http://localhost:19455',
  headers:
   { 'accept-encoding': [ 'gzip,deflate' ],
     'user-agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
     connection: [ 'close' ],
     accept: [ '*/*' ],
     'content-length': [ 195 ] },
  redirect: 'follow',
  method: 'POST',
  host: 'localhost',
  _agentKey: 'localhost:19455:' }
HTTP 1944: sockets localhost:19455: 1
HTTP 1944: write ret = false
HTTP 1944: outgoing message end.
HTTP 1944: AGENT incoming response!
HTTP 1944: AGENT isHeadResponse false
{ Error: Bad Request
    at new NetworkResponseStatusCodeError (/Users/dunnkers/Documents/git/ing-api/ing-api/node_modules/keepasshttp-client/model/common.js:36:28)
    at KeePassHttpClient.<anonymous> (/Users/dunnkers/Documents/git/ing-api/ing-api/node_modules/keepasshttp-client/client.js:133:35)
    at step (/Users/dunnkers/Documents/git/ing-api/ing-api/node_modules/tslib/tslib.js:131:27)
    at Object.next (/Users/dunnkers/Documents/git/ing-api/ing-api/node_modules/tslib/tslib.js:112:57)
    at fulfilled (/Users/dunnkers/Documents/git/ing-api/ing-api/node_modules/tslib/tslib.js:102:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) statusCode: 400 }
HTTP 1944: CLIENT socket onClose
HTTP 1944: removeSocket localhost:19455: writable: false
HTTP 1944: HTTP socket close
```

When running this code:
```js
const { KeePassHttpClient } = require("keepasshttp-client");
const client = new KeePassHttpClient();

client.associate()
    .then(() => client.getLogins({ url: 'twitter.com' }))
    .then((records) => console.log(JSON.stringify(records, null, 2)))
    .catch((err) => console.error(err));
```

Thanks for diving into this. There has to be some small miscommunication between `keepasshttp-client` and the MacPass KeePassHTTP Plugin's Server. This is weird because it should all run the same KeePassHTTP protocol. MacPass does work with Safari plugins [passafari](https://github.com/mmichaa/passafari.safariextension/), [KeePassHelper](https://safari-extensions.apple.com/details/?id=com.add0n.keepass-RED8XKG2R4) and Chrome plugins [chromeIPass](https://chrome.google.com/webstore/detail/chromeipass/ompiailgknfdndiefoaoiligalphfdae), [KeePass Tusk](https://chrome.google.com/webstore/detail/keepass-tusk-a-better-pas/fmhmiaejopepamlcjkncpgpdjichnecm) for example, which suggests that there is no error in the protocol on MacPass's side. There might be a protocol error somewhere else?

Regards. ✌🏻

**Comment by dunnkers** [comment]
**BTW** my KeePassHTTP Server was running in the execution of that code 👆🏻

**Comment by vladimiry** [comment]
@dunnkers  Just tried to debug it running the same code. I get `outgoing message end.` after key entering dialog window showing and `AGENT isHeadResponse false` line after entering key name in that dialog window and clicking "ok" (MacPass might have another button name). So applying the same log lines sequence to your case I can assume that you got key entering dialog shown, did you?

What happens if you run just `associate`? Such code:
```javascript
const {KeePassHttpClient} = require("keepasshttp-client");
const client = new KeePassHttpClient(/*{url: "http://localhost:19455"}*/);

client.associate()
    .then(console.log)
    .catch(console.error);
```

Also try to execute `getLogins` method with uri scheme specified, like `.getLogins({url: "https://twitter.com"});` or `.getLogins({url: "http://twitter.com"});`.

Btw try to use previous version of your plugin/tools https://github.com/MacPass/MacPassHTTP/issues/48

**Comment by dunnkers** [comment]
Using your code to only just run `associate()` already throws a `Bad Request` error. The [keepass-http-client](https://github.com/michoelchaikin/keepass-http-client) package, however, does work correctly with MacPass. There's probably a difference in implementation in that package and yours?

**Comment by vladimiry** [comment]
The apparent difference is in http request libraries used, I prefer to use much more lightweight library than `request-promise-native`. Here is the revision of this module 9d9da85c21580953506e93d71de90ef7d600039c that used `request-promise-native` module if you want to try it. Meanwhile going to debug the http request difference, I guess it's in the request headers.

**Comment by vladimiry** [comment]
@dunnkers can you try just recently posted 2.2.5 version.

**Comment by dunnkers** [comment]
Excellent! It works now!

![kapture 2018-01-23 at 0 45 19](https://user-images.githubusercontent.com/744430/35250439-e2dcfd28-ffd6-11e7-9e1f-d1b06ca4a922.gif)

After obtaining a key from MacPass, I'm able to retrieve some example username/password. Nice ✌🏻

**Comment by vladimiry** [comment]
Ok, closing then.

**Comment by dunnkers** [comment]
I think we can consider this issue closed!
